services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: burhan
      POSTGRES_PASSWORD: burhan123
      POSTGRES_DB: burhan
    ports:
      - "55432:5432"
    volumes:
      - burhan_pg:/var/lib/postgresql/data

volumes:
  burhan_pg:
